---
kind: ReplicationController
apiVersion: v1
metadata:
  name: python-app-2
spec:
  replicas: 3
  template:
    metadata:
      labels:
        role: python-app-2
    spec:
      containers:
        - name: python-app-2
          imagePullPolicy: Always
          image: 917550314955.dkr.ecr.us-west-2.amazonaws.com/python-app-2:latest
          livenessProbe:
            httpGet:
              path: /health_check
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3

---
kind: Service
apiVersion: v1
metadata:
  name: python-app-2
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    role: python-app-2

---
apiVersion: v1
kind: Service
metadata:
  name: python-app-2-exposed
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30100
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    role: python-app-2
  type: NodePort
